{"hash":"f38b440b6d1b4c23593bb19e805e9051223023a1","data":{"post":{"title":"cleo ReDoS","path":"/vulnerabilities/cleo-redos-xray-257186/","content":"<h2 id=\"summary\"><a href=\"#summary\" aria-hidden=\"true\" tabindex=\"-1\">Summary</a></h2>\n<p>Exponential ReDoS in cleo leads to denial of service</p>\n<h2 id=\"component\"><a href=\"#component\" aria-hidden=\"true\" tabindex=\"-1\">Component</a></h2>\n<p><a href=\"https://pypi.org/project/cleo\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">cleo</a></p>\n<h2 id=\"affected-versions\"><a href=\"#affected-versions\" aria-hidden=\"true\" tabindex=\"-1\">Affected versions</a></h2>\n<p>cleo (,)</p>\n<h2 id=\"description\"><a href=\"#description\" aria-hidden=\"true\" tabindex=\"-1\">Description</a></h2>\n<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the cleo PyPI package, when an attacker is able to supply arbitrary input to the <code>cleo</code> method</p>\n<h2 id=\"poc\"><a href=\"#poc\" aria-hidden=\"true\" tabindex=\"-1\">PoC</a></h2>\n<p>No PoC is supplied for this issue</p>\n<h2 id=\"vulnerability-mitigations\"><a href=\"#vulnerability-mitigations\" aria-hidden=\"true\" tabindex=\"-1\">Vulnerability Mitigations</a></h2>\n<p>No mitigations are supplied for this issue</p>\n<h2 id=\"references\"><a href=\"#references\" aria-hidden=\"true\" tabindex=\"-1\">References</a></h2>\n<p><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42966\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">NVD</a></p>\n","description":"CVE-2022-42966 Medium severity. Exponential ReDoS in cleo leads to denial of service","date_published":"2022-10-15","xray_id":"XRAY-257186","vul_id":"CVE-2022-42966","severity":"medium","discovered_by":"Denys Vozniuk","last_updated":"2022-10-15","cvss":5.9}},"context":{}}